apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: docker4fiki/auth
      context: services/auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker4fiki/tickets
      context: services/tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker4fiki/orders
      context: services/orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker4fiki/expiration
      context: services/expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker4fiki/payments
      context: services/payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./config/k8s/*
deploy:
  kubectl: {}
