apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: docker4fiki/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    # - image: docker4fiki/client
    #   context: client
    #   sync:
    #     manual:
    #       - src: "**/*.ts"
    #         dest: .
    #       - src: "**/*.scss"
    #         dest: .
    #       - src: "**/*.tsx"
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile
    - image: docker4fiki/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker4fiki/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker4fiki/expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker4fiki/payments
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    concurrency: 1
manifests:
  rawYaml:
    - ./config/k8s/*
deploy:
  kubectl: {}
