apiVersion: v1
data:
  JWT_KEY: "MTIz"
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
---
apiVersion: v1
data:
  STRIPE_KEY: "MTIz"
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
---