name: eslint-client

on:
  pull_request:
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd client && npm install && npm run lint:eslint
